site_name: TreeDy Stack

theme: 
  name: material
  palette:
    - primary: teal

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  # The header
  features:
    # Autohide the header
    - header.autohide

    # For navigation
    - navigation.tabs
    - navigation.tracking
    - navigation.instant
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.footer
  # Extending the theme
  custom_dir: overides

  # Github Icon
  icon:
    repo:fontawesome/brands/git-alt

repo_url: https://github.com/Treedy2020/TreeDyStack
repo_name: Treedy2020/TreeDyStack

plugins:
  - search
  - macros
  - markmap
  - glightbox
  # Social Cards Part
  - social
  - tags

nav:
  - Home: 'index.md'
  - Blogs: 
    - './blogs/streamlit.md'
    - './blogs/FactorViewer.md'
    - './blogs/DistributedTraining.md'
    - './blogs/PaddlePaddle.md'
markdown_extensions:

  # Annotations Part
  - attr_list
  - md_in_html

  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite

  # Admonition Part
  - admonition
  - pymdownx.details

  # Content Tabs
  - pymdownx.tabbed:
      alternate_style: true

  # Images
  - md_in_html

  # Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  
  # Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # Code Blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite

  # Tooltips
  - abbr
  - pymdownx.snippets

  # Emoji and Icons
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  
  # Mermaid 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Extra Part
extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk
      name: TreeDy2020
  generator: true
# Copy Right
copyright: Copyright &copy; 2020-2025 TreeDy Donate
